version: 2

sources:
  - name: raw_data
    description: "Raw data for taxi rides"
    database: dtc-de-course-487301 # project ID
    schema: ng_test_dataset # dataset name
    # the tables in data warehouse
    tables:
      - name: yellow_tripdata
        description: Raw yellow taxi trip data
        columns:
          - name: VendorID
            description: A code indicating the provider associated with trip record
            data_type: integer

      - name: green_tripdata
        description: Raw green taxi trip data
